version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=raybrendo@hotmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "5678:5678"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: n8n
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=12345
      - N8N_HOST=n8n.raybrendo.online
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.raybrendo.online`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
    volumes:
      - ./n8n:/home/node/.n8n
    depends_on:
      - postgres

  osrm-prep:
    image: osrm/osrm-backend
    command: >
      bash -c "osrm-extract -p /opt/car.lua /data/manaus.osm.pbf &&
               osrm-partition /data/manaus.osrm &&
               osrm-customize /data/manaus.osrm"
    volumes:
      - ./osrm-data:/data

  osrm:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/manaus.osrm
    volumes:
      - ./osrm-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.osrm.rule=Host(`osrm.raybrendo.online`)"
      - "traefik.http.routers.osrm.entrypoints=websecure"
      - "traefik.http.routers.osrm.tls.certresolver=myresolver"
    depends_on:
      - osrm-prep

  frontend:
    image: nginx:alpine
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.raybrendo.online`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
